"""Generate a NEW immutable migration snapshot from the current visit contract."""
import json
from pathlib import Path
import sys

from sales_backend.contracts.visit_schema import FIELD_VERSION, FORM_DEFINITION_ID, FORM_VERSION_ID, schema_snapshot

TARGET = Path(__file__).resolve().parents[2]/"database/migrations/V042__visit_contract_v3.sql"


def render():
    snapshot = json.dumps(schema_snapshot(), ensure_ascii=False, sort_keys=True)
    return f'''-- Generated by backend/scripts/export_visit_contract.py; never edit after application.
BEGIN;
ALTER TABLE activity.visit ADD COLUMN recorded_on date;
ALTER TABLE activity.visit ADD COLUMN archived_fields jsonb NOT NULL DEFAULT '{{}}';
COMMENT ON COLUMN activity.visit.recorded_on IS '销售在新版日期组件选择的填写日期；区别于不可伪造的系统 created_at';
COMMENT ON COLUMN activity.visit.archived_fields IS '归档时人工确认的原始字段快照，归档后不因补充或客户资料修改而覆盖';
UPDATE activity.visit v SET archived_fields=COALESCE((SELECT jsonb_object_agg(d.field_key,f.value_json)
 FROM activity.visit_field_value f JOIN config.field_definition d ON d.id=f.field_definition_id
 WHERE f.visit_id=v.id),'{{}}'::jsonb), recorded_on=timezone('Asia/Shanghai',v.created_at)::date;
INSERT INTO config.form_version(id,form_definition_id,version_no,status,schema_snapshot)
SELECT '{FORM_VERSION_ID}','{FORM_DEFINITION_ID}',COALESCE(max(version_no),0)+1,'active',
$schema${snapshot}$schema$::jsonb
FROM config.form_version WHERE form_definition_id='{FORM_DEFINITION_ID}';
INSERT INTO config.field_definition(id,object_type,field_key,label,data_type,is_system,version_no)
SELECT (f->>'id')::uuid,'visit',f->>'field_key',f->>'label',f->>'data_type',true,{FIELD_VERSION}
FROM config.form_version v CROSS JOIN LATERAL jsonb_array_elements(v.schema_snapshot->'fields') f
WHERE v.id='{FORM_VERSION_ID}';
INSERT INTO config.form_version_field(form_version_id,field_definition_id,display_order,is_required,is_readonly,ui_config)
SELECT v.id,(f->>'id')::uuid,n,(f->>'is_required')::boolean,(f->>'is_readonly')::boolean,
 jsonb_build_object('first_visit_required',(f->>'first_visit_required')::boolean)
FROM config.form_version v CROSS JOIN LATERAL jsonb_array_elements(v.schema_snapshot->'fields') WITH ORDINALITY a(f,n)
WHERE v.id='{FORM_VERSION_ID}';
CREATE FUNCTION activity.preserve_visit_archive() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF OLD.status='archived' AND (NEW.archived_fields IS DISTINCT FROM OLD.archived_fields
   OR NEW.form_version_id IS DISTINCT FROM OLD.form_version_id OR NEW.created_at IS DISTINCT FROM OLD.created_at) THEN
  RAISE EXCEPTION '已归档快照、表单版本和系统创建时间不可修改' USING ERRCODE='23514';
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER preserve_visit_archive BEFORE UPDATE ON activity.visit
 FOR EACH ROW EXECUTE FUNCTION activity.preserve_visit_archive();
INSERT INTO ops.schema_migration(version,description) VALUES('V042','新版拜访字段契约、填写日期与不可变归档快照');
COMMIT;
'''


if __name__ == "__main__":
    if "--check" in sys.argv:
        if TARGET.read_text()!=render(): raise SystemExit("Current visit contract and generated migration disagree")
    else:
        TARGET.write_text(render())
