import assert from 'node:assert/strict';
import {mkdir, writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {join} from 'node:path';

// UI-only acceptance: no application-state mutation or direct API submissions.
// Run after npm run build with the local server available on port 5186.
const {chromium, expect} = await import(process.env.PLAYWRIGHT_MODULE || '@playwright/test');
const root = fileURLToPath(new URL('..', import.meta.url));
const out = join(root, '.runtime', 'flow-verification');
const base = process.env.APP_URL || 'http://127.0.0.1:5186';
assert.ok(['localhost', '127.0.0.1', '[::1]'].includes(new URL(base).hostname), 'Synthetic flow verification is local only');
await mkdir(out, {recursive: true});
const browser = await chromium.launch({headless: true, channel: 'chrome'});
const checks = [], errors = [], apiRequests = [];
const sample = '沟通内容：今天与客户讨论试点范围，对方确认先评估两条产线，尚未确认采购金额。\n下一步计划：2026-09-18由我整理试点范围并发送验收清单给客户。\n跟进日期：2026-09-14\n对接人：示例联系人甲';
const revised = '今天与客户讨论试点范围，对方确认先评估两条产线，尚未确认采购金额。人工补充：双方约定先验证数据口径。';
const next = '2026-09-18由我整理试点范围并发送验收清单给客户。';
const fdeBody = 'FDE与客户核对样本字段和测试环境，客户同意先提供脱敏样本做演示。';
let page;
try {
  page = await browser.newPage({viewport: {width: 1440, height: 1100}});
  page.setDefaultTimeout(12000);
  page.on('pageerror', error => errors.push(error.message));
  page.on('request', request => {if (new URL(request.url()).pathname.startsWith('/api/v1')) apiRequests.push({method: request.method(), path: new URL(request.url()).pathname});});
  const button = name => page.getByRole('button', {name, exact: true});
  const shot = async filename => {
    // Scroll the viewport only; never call application state or business handlers.
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.screenshot({path: join(out, filename)});
  };
  const main = page.getByRole('main', {name: '业务页面'});
  await page.goto(base + '/?mode=preview');
  await expect(page.getByRole('combobox', {name: '示例身份', exact: true})).toHaveValue('sales');
  await button('记录客户拜访').click();
  await button('【 【示例】星河制造 示例协作一组 选择').click();
  await page.getByPlaceholder('可以说说：这次为什么拜访、客户反馈了什么、接下来准备何时做什么……').fill(sample);
  await button('提交结构化').click();
  await expect(page.getByPlaceholder('填写本次沟通的客户对接人')).toHaveValue('示例联系人甲');
  await expect(button('确认并归档')).toBeEnabled();
  await expect(main).toContainText('未调用真实 Agent');
  await shot('visit-sales-01-structured.png');
  checks.push('sales labelled original text fills confirmation fields without guessed next step');
  await page.getByPlaceholder('实际沟通内容、客户反馈和达成结果').fill(revised);
  await expect(button('确认并归档')).toBeDisabled();
  await expect(main).toContainText('已修改');
  await shot('visit-sales-02-stale-review.png');
  checks.push('editing visit body invalidates the old field check and disables archive');
  await button('执行本地字段检查').click();
  await expect(button('确认并归档')).toBeEnabled();
  await page.getByPlaceholder('明确时间、负责人和具体行动').fill('由我整理试点范围并发送验收清单给客户。');
  await button('执行本地字段检查').click();
  await expect(button('确认并归档')).toBeDisabled();
  await expect(main).toContainText('待补充：下一步包含日期');
  await shot('visit-sales-03-missing-date.png');
  checks.push('missing next-action date fails field check and blocks archive');
  await page.getByPlaceholder('明确时间、负责人和具体行动').fill(next);
  await button('执行本地字段检查').click();
  await expect(button('确认并归档')).toBeEnabled();
  await shot('visit-sales-04-rechecked.png');
  await button('确认并归档').click();
  await expect(page.getByRole('dialog')).toContainText('商机：不关联商机');
  await shot('visit-sales-05-human-confirm.png');
  await button('确认归档').click();
  await expect(main).toContainText('拜访记录录入成功');
  await shot('visit-sales-06-archived.png');
  await button('查看客户档案 ›').click();
  await button('拜访记录').click();
  await page.getByRole('button', {name: /待确认 展开 客户沟通记录 待确认 记录人 示例销售$/}).click();
  await expect(main).toContainText(revised); await expect(main).toContainText(next);
  await expect(main).toContainText('2026年9月14日'); await expect(main).toContainText('示例联系人甲');
  await shot('visit-sales-07-readback.png');
  checks.push('sales human confirmation archives and original customer page reads back revised text plus next action');
  await page.reload();
  await button('拜访记录').click();
  await page.getByRole('button', {name: /待确认 展开 客户沟通记录 待确认 记录人 示例销售$/}).click();
  await expect(main).toContainText(revised);
  checks.push('refresh preserves route and locally archived visit');
  await page.getByRole('combobox', {name: '示例身份', exact: true}).selectOption('fde');
  await expect(page.getByRole('combobox', {name: '示例身份', exact: true})).toHaveValue('fde');
  await button('记录客户拜访').click();
  await button('【 【示例】星河制造 示例协作一组 选择').click();
  await expect(button('请先选择本人参与的商机')).toBeDisabled();
  await shot('visit-fde-01-opportunity-required.png');
  await button('【示例】智能质检试点 选择').click();
  await page.getByPlaceholder('可以说说：这次为什么拜访、客户反馈了什么、接下来准备何时做什么……').fill(`沟通内容：${fdeBody}\n下一步计划：2026-09-19由我整理测试接口清单并发送给项目负责人。\n跟进日期：2026-09-14\n对接人：示例技术联系人`);
  await button('提交结构化').click();
  await expect(page.getByPlaceholder('填写本次沟通的客户对接人')).toHaveValue('示例技术联系人');
  await expect(main).toContainText('只显示你本人在协助名单中的商机');
  await expect(main).toContainText('【示例】智能质检试点');
  await expect(button('确认并归档')).toBeEnabled();
  await shot('visit-fde-02-structured.png');
  await button('确认并归档').click();
  await expect(page.getByRole('dialog')).toContainText('商机：【示例】智能质检试点');
  await button('确认归档').click();
  await expect(main).toContainText('拜访记录录入成功');
  await shot('visit-fde-03-archived.png');
  await button('查看客户档案 ›').click();
  await button('拜访记录').click();
  await page.getByRole('button', {name: /待确认 展开 【示例】智能质检试点 待确认 记录人 示例FDE$/}).click();
  await expect(main).toContainText(fdeBody);
  await expect(main).toContainText('2026年9月14日'); await expect(main).toContainText('示例技术联系人');
  await expect(main).toContainText('2026-09-19由我整理测试接口清单并发送给项目负责人。');
  await shot('visit-fde-04-readback.png');
  checks.push('FDE requires own participating opportunity; confirmation, archive and readback preserve linkage and recorder');
  assert.deepEqual(errors, []); assert.deepEqual(apiRequests, [], 'Preview must not contact live APIs');
  checks.push('no page errors and no real API requests during synthetic workflow');
  const result = {verified_at: new Date().toISOString(), level: '合成示例正常 UI 业务流程', checks, errors, real_api_requests: apiRequests, live_backend_verified: false, agent_verified: false};
  await writeFile(join(out, 'visit-result.json'), JSON.stringify(result, null, 2));
  console.log(JSON.stringify(result, null, 2));
} catch (error) {
  if (page) await page.screenshot({path: join(out, 'visit-failure.png'), fullPage: true}).catch(() => {});
  throw error;
} finally {await browser.close();}
