-- Reviewed baseline ACL metadata from the matching V125 source runtime.
-- No passwords, role attributes, business rows or source identities copied.
-- Apply only on the new Shenma database as maintainer after migrations.
-- Runtime role must already exist with NOSUPERUSER NOBYPASSRLS.
BEGIN;
GRANT EXECUTE ON FUNCTION activity.capture_visit_recording_identity() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION crm.attach_customer_owner() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION crm.initialize_customer_ownership() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION ops.audit_business_row() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION ops.audit_feishu_config() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION ops.audit_participation_row() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION ops.capture_audit_identity() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION ops.capture_feishu_event() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION ops.claim_job(p_worker_id text, p_lock_seconds integer) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION ops.claim_job(p_worker_id text, p_lock_seconds integer, p_job_types text[], p_exclude_types boolean) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION ops.enqueue_daily_sales_competency_reviews() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION ops.evaluate_ai_usage_alerts() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION ops.prune_system_events() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION ops.record_system_event(p_workspace uuid, p_actor uuid, p_request uuid, p_level text, p_module text, p_event text, p_detail text, p_stack text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION ops.reject_invalid_job_actor(p_job_id uuid, p_lease_token uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION ops.run_priority_reminder_monitor() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.account_has_password(p_user uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.account_login_status(p_user uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.account_supervisor_title(p_workspace uuid, p_user uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.account_team_scope(p_workspace uuid, p_user uuid, p_role text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.active_company_rule(p_code text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.add_customer_sales_member(p_customer_id uuid, p_user_id uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.agent_operation_rows(p_start timestamp with time zone, p_end timestamp with time zone) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.agent_operation_rows_v066(p_start timestamp with time zone, p_end timestamp with time zone) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.ai_invocation_report(p_start timestamp with time zone, p_end timestamp with time zone, p_role text, p_user uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.auth_session_is_active(p_session_id uuid, p_workspace_id uuid, p_user_ref_id uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.bump_fde_membership_version(p_opportunity uuid, p_expected_version integer) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.business_activity_rows(p_start timestamp with time zone, p_end timestamp with time zone) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.business_ranking(p_metric text, p_start date, p_end date, p_months integer[], p_self_only boolean) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.can_claim_customer(p_customer_id uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.can_manage_fde_members(p_opportunity uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.can_write_demo_scene(p_opportunity uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.can_write_visit(p_visit uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.change_own_password(p_old_hash text, p_new_hash text, p_session uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.check_crm_import_target(p_record uuid, p_target uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.claim_customer(p_customer_id uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.claim_notification(p_recipient uuid, p_customer uuid, p_event uuid, p_title text, p_body text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.company_customer_directory(p_query text, p_limit integer, p_offset integer) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.company_customer_directory_page(p_query text, p_limit integer, p_offset integer) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.company_directory() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.company_management_actor(p_target uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.complete_password_login(p_session uuid, p_hash text, p_attempt_key text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.create_auth_session(p_session_id uuid, p_workspace_id uuid, p_user_ref_id uuid, p_refresh_token_hash text, p_expires_at timestamp with time zone, p_client_context jsonb) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.crm_history_visit_form_valid(p_form uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.customer_claim_pool(p_query text, p_limit integer) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.customer_portfolio_scope() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.customer_reference(p_customer_id uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.customer_risk_assessment_owner(p_customer uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.dashboard_subject_ranking(p_metric text, p_start date, p_end date, p_months integer[], p_member uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.demo_scene_history(p_scene uuid, p_limit integer, p_offset integer) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.fde_can_act_on_task(p_task uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.fde_can_coordinate_task(p_task uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.fde_can_record_opportunity(p_opportunity uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.fde_can_record_task_response(p_task uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.fde_customer_in_scope(p_customer uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.fde_dashboard_rankings(p_start date, p_end date, p_quarters integer[], p_member uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.fde_demo_statistics(p_users uuid[], p_opportunities uuid[], p_start timestamp with time zone, p_end timestamp with time zone, p_quarters integer[]) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.fde_manages_user(p_user uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.fde_opportunity_in_scope(p_opportunity uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.fde_participation_history() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.fde_peer_rankings(p_start date, p_end date, p_quarters integer[]) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.fde_permission_version() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.fde_profile_history(p_user uuid, p_days integer, p_limit integer) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.fde_recorded_visit_history() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.fde_recorded_visit_history(p_start timestamp with time zone, p_end timestamp with time zone, p_user uuid, p_opportunity uuid, p_quarters integer[]) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.fde_task_eligible(p_task uuid, p_user uuid, p_role text, p_team uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.fde_user_direct_opportunity_scope(p_user uuid, p_role text, p_team uuid, p_opportunity uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.fde_user_has_opportunity_access(p_user uuid, p_opportunity uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.fde_user_is_active(p_user uuid, p_role text, p_team uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.fde_visit_entry_enabled() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.feishu_initialize(p_connection uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.feishu_notification_test_archive(p_descriptor jsonb, p_expected_plan text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.feishu_notification_test_archive_v2(p_descriptor jsonb, p_expected_plan text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.feishu_recover(p_connection uuid, p_event uuid, p_action text, p_key text, p_note text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.feishu_test_archive(p_manifest jsonb, p_expected_plan text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.get_password_policy() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.guard_account_phone_collision() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.has_active_role(p_role_code text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.has_analysis_scope(p_identity jsonb, p_version smallint) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.has_customer_access(p_customer_id uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.has_customer_write_access(p_customer_id uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.has_feishu_credential(p_connection uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.has_linked_visit_access(p_visit uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.has_opportunity_access(p_opportunity_id uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.has_opportunity_read_access(p_opportunity uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.has_partner_followup_access(p_partner uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.is_fde_actor() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.lock_password_login_identifier(p_identifier text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.login_attempt(p_key text, p_limit integer) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.login_limit_status(p_key text, p_limit integer) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.management_actor() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.model_usage_summary(p_days integer) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.opportunity_name_is_available(p_customer_id uuid, p_name text, p_exclude_id uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.opportunity_owner_in_scope(p_user_id uuid, p_team_id uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.own_password_candidate() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.password_account_workspace(p_account text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.password_candidate(p_workspace text, p_account text, p_role text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.password_login_identifier(p_workspace text, p_identifier text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.prepare_feishu_migration(p_connection uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.profile_customer_owner(p_customer uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.profile_scope_allowed(p_scope text, p_user uuid, p_team uuid, p_write boolean) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.protect_managed_account() TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.publish_company_rule(p_id uuid, p_revision integer) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.release_customer(p_customer uuid, p_version integer, p_reason text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.resolve_account_actor(p_workspace_external_id text, p_account_code text, p_role text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.resolve_demo_actor(p_workspace_external_id text, p_account_code text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.resolve_legacy_customer_owner(p_customer uuid, p_version integer, p_owner uuid, p_reason text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.restore_historical_customer_ownership(p_record uuid, p_user uuid, p_team uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.review_customer_claim(p_request uuid, p_decision text, p_reason text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.review_target_batch(p_request uuid, p_decision text, p_reason text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.review_target_change(p_request uuid, p_decision text, p_reason text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.revoke_auth_session(p_session_id uuid, p_workspace_id uuid, p_user_ref_id uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.revoke_managed_account_sessions(p_user uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.rotate_auth_session(p_old_hash text, p_new_hash text, p_new_expires_at timestamp with time zone) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.save_company_rule(p_code text, p_name text, p_definition jsonb, p_reason text, p_id uuid, p_revision integer, p_base uuid, p_restored uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.save_period_target(p_scope text, p_user uuid, p_team uuid, p_period text, p_start date, p_end date, p_kind text, p_amount numeric, p_version integer) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.save_target_batch(p_scope text, p_user uuid, p_team uuid, p_period text, p_start date, p_end date, p_items jsonb, p_reason text, p_department_code text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.session_credentials(p_session uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.set_account_password(p_user uuid, p_hash text, p_must_change boolean) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.set_feishu_credential(p_connection uuid, p_cipher bytea, p_key text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.set_password_policy(p_required boolean, p_version bigint) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.supervises_team(p_team_id uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.target_scope_read(p_scope text, p_user uuid, p_team uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.target_scope_read(p_scope text, p_user uuid, p_team uuid, p_department_code text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.target_scope_write(p_scope text, p_user uuid, p_team uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.target_scope_write(p_scope text, p_user uuid, p_team uuid, p_department_code text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.task_actor_recipient(p_task uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.task_link_context(p_task uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.task_recipient_eligible(p_task uuid, p_user uuid, p_role text, p_team uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.unlock_account_login(p_user uuid, p_reason text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.visit_opportunities_readable(p_visit uuid, p_legacy_opportunity uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION security.visit_opportunities_writable(p_visit uuid, p_legacy_opportunity uuid) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION workflow.complete_business_review(p_event uuid, p_review jsonb) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION workflow.complete_opportunity_change_review(p_event uuid, p_review jsonb) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION workflow.enqueue_battle_map_leader_notifications(p_workspace_id uuid, p_customer_id uuid, p_trigger_id uuid, p_title text, p_body text, p_potential_score numeric, p_relationship_score numeric, p_quadrant_code text) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION workflow.enqueue_fde_collaboration_notification(p_opportunity uuid, p_recipient uuid, p_template text, p_event uuid, p_payload jsonb) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION workflow.enqueue_task_notification(p_workspace_id uuid, p_recipient_user_ref_id uuid, p_template_code text, p_title text, p_body text, p_task_id uuid, p_dedupe_key text, p_payload jsonb) TO shenma_runtime;
GRANT EXECUTE ON FUNCTION workflow.notify_fde_membership() TO shenma_runtime;
GRANT USAGE ON SCHEMA activity TO shenma_runtime;
GRANT USAGE ON SCHEMA agent TO shenma_runtime;
GRANT USAGE ON SCHEMA common TO shenma_runtime;
GRANT USAGE ON SCHEMA config TO shenma_runtime;
GRANT USAGE ON SCHEMA crm TO shenma_runtime;
GRANT USAGE ON SCHEMA insight TO shenma_runtime;
GRANT USAGE ON SCHEMA ops TO shenma_runtime;
GRANT USAGE ON SCHEMA platform TO shenma_runtime;
GRANT USAGE ON SCHEMA security TO shenma_runtime;
GRANT USAGE ON SCHEMA workflow TO shenma_runtime;
GRANT SELECT,USAGE ON SEQUENCE ops.audit_log_id_seq TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE activity.action_item TO shenma_runtime;
GRANT SELECT ON TABLE activity.v_visit_collaborators TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE activity.v_visit_timeline TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE activity.visit TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE activity.visit_contact TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE activity.visit_field_value TO shenma_runtime;
GRANT DELETE,INSERT,SELECT,UPDATE ON TABLE activity.visit_import TO shenma_runtime;
GRANT DELETE,INSERT,SELECT ON TABLE activity.visit_import_content TO shenma_runtime;
GRANT DELETE,INSERT,SELECT ON TABLE activity.visit_opportunity TO shenma_runtime;
GRANT DELETE,INSERT,SELECT,UPDATE ON TABLE activity.visit_participant TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE agent.artifact TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE agent.confirmation TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE agent.conversation TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE agent.inference_operation TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE agent.message TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE agent.model_invocation TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE agent.run TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE agent.run_step TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE agent.tool_invocation TO shenma_runtime;
GRANT SELECT ON TABLE config.agent_definition TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE config.agent_runtime_config TO shenma_runtime;
GRANT INSERT,SELECT ON TABLE config.agent_runtime_release TO shenma_runtime;
GRANT SELECT ON TABLE config.dictionary TO shenma_runtime;
GRANT SELECT ON TABLE config.dictionary_item TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE config.feishu_connection TO shenma_runtime;
GRANT SELECT ON TABLE config.field_definition TO shenma_runtime;
GRANT SELECT ON TABLE config.form_definition TO shenma_runtime;
GRANT SELECT ON TABLE config.form_version TO shenma_runtime;
GRANT SELECT ON TABLE config.form_version_field TO shenma_runtime;
GRANT SELECT ON TABLE config.metric_definition TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE config.model_api_current TO shenma_runtime;
GRANT INSERT,SELECT ON TABLE config.model_api_release TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE config.model_api_test TO shenma_runtime;
GRANT SELECT ON TABLE config.prompt_template TO shenma_runtime;
GRANT SELECT ON TABLE config.rule_set TO shenma_runtime;
GRANT SELECT ON TABLE config.sales_competency_framework TO shenma_runtime;
GRANT INSERT,SELECT ON TABLE crm.business_change TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE crm.contact TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE crm.customer TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE crm.customer_actual TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE crm.customer_assignment TO shenma_runtime;
GRANT SELECT ON TABLE crm.customer_claim_request TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE crm.customer_duplicate_candidate TO shenma_runtime;
GRANT SELECT ON TABLE crm.customer_ownership TO shenma_runtime;
GRANT SELECT ON TABLE crm.customer_ownership_event TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE crm.customer_product TO shenma_runtime;
GRANT SELECT ON TABLE crm.customer_sales_member TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE crm.opportunity TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE crm.opportunity_demo_scenes TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE crm.opportunity_forecast TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE crm.opportunity_participant TO shenma_runtime;
GRANT INSERT,SELECT ON TABLE crm.opportunity_period_actual_snapshot TO shenma_runtime;
GRANT INSERT,SELECT ON TABLE crm.opportunity_quote_reference TO shenma_runtime;
GRANT DELETE,INSERT,SELECT ON TABLE crm.opportunity_related_partner TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE crm.partner TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE crm.product TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE crm.sales_target TO shenma_runtime;
GRANT SELECT ON TABLE crm.sales_target_batch_request TO shenma_runtime;
GRANT SELECT ON TABLE crm.sales_target_change_request TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE crm.v_customer_current_quadrant TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE insight.business_advice TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE insight.business_suggestion TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE insight.customer_risk_assessment TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE insight.quadrant_score TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE insight.recommendation TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE insight.report TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE insight.risk TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE insight.risk_event TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE insight.sales_competency_review TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE insight.v_open_risk_summary TO shenma_runtime;
GRANT SELECT ON TABLE ops.ai_usage_alert TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE ops.ai_usage_rule TO shenma_runtime;
GRANT INSERT,SELECT ON TABLE ops.audit_log TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE ops.crm_import_batch TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE ops.crm_import_binding TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE ops.crm_import_record TO shenma_runtime;
GRANT SELECT ON TABLE ops.feishu_config_audit TO shenma_runtime;
GRANT SELECT ON TABLE ops.feishu_delivery TO shenma_runtime;
GRANT SELECT ON TABLE ops.feishu_event TO shenma_runtime;
GRANT SELECT ON TABLE ops.feishu_record_map TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE ops.file_asset TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE ops.idempotency_key TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE ops.job TO shenma_runtime;
GRANT INSERT,SELECT ON TABLE ops.job_effect TO shenma_runtime;
GRANT INSERT,SELECT ON TABLE ops.mutation_receipt TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE ops.outbox_event TO shenma_runtime;
GRANT SELECT ON TABLE ops.system_event TO shenma_runtime;
GRANT SELECT ON TABLE ops.v_schema_catalog TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE platform.auth_session TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE platform.identity_binding TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE platform.role_binding TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE platform.team TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE platform.team_membership TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE platform.user_ref TO shenma_runtime;
GRANT SELECT ON TABLE platform.workspace TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE workflow.notification TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE workflow.notification_delivery TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE workflow.task TO shenma_runtime;
GRANT DELETE,INSERT,SELECT,UPDATE ON TABLE workflow.task_assignee TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE workflow.task_candidate TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE workflow.task_event TO shenma_runtime;
GRANT SELECT ON TABLE workflow.v_task_action_recipient TO shenma_runtime;
GRANT INSERT,SELECT,UPDATE ON TABLE workflow.v_user_inbox TO shenma_runtime;
SELECT security.reconcile_runtime_grants();
COMMIT;
