"""Run historical V108 archive tests in their exact disposable schema.

Usage (local PostgreSQL owner session only):
  PGHOST=/local/test/socket PGPORT=55469 PGUSER=postgres \
    uv run --extra dev python tests/system/run_feishu_archive_v108_postgres.py

Current V117 intentionally rejects the V108 entry point. Do not weaken that
production gate to make old success tests run on a newer schema. This runner
uses unchanged baseline/seeds and migration files through V108, then delegates
database/role creation and cleanup to the standard integration runner.
"""
import asyncio
import os
import sys
from pathlib import Path
from tempfile import TemporaryDirectory
from urllib.parse import quote, urlencode
from xml.etree import ElementTree

BACKEND = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(BACKEND))
from tests.system import run_integration_postgres as runner  # noqa: E402


async def main(version=108):
    if version not in {108,117}:
        raise ValueError("Only audited historical archive versions are supported")
    host = os.environ.get("PGHOST", "")
    if not (host.startswith("/") or host in {"127.0.0.1", "localhost", "::1"}):
        raise RuntimeError("Historical archive verification requires a local disposable PostgreSQL server")
    source = runner.ROOT / "database"
    original_migrate = runner.migrate
    with TemporaryDirectory(prefix=f"salegent-feishu-v{version}-schema-") as temp:
        root = Path(temp)
        for directory in ("baseline", "seeds"):
            (root / directory).symlink_to(source / directory, target_is_directory=True)
        (root / "migrations").mkdir()
        for directory in (source, source / "migrations"):
            for path in directory.glob("V*.sql"):
                if int(path.name.split("__", 1)[0][1:]) <= version:
                    target = root / ("migrations" if directory.name == "migrations" else "") / path.name
                    target.symlink_to(path)

        async def migrate_v108(connection):
            return await original_migrate(connection, root=root)

        async def verify(config, name, role):
            user = quote(config["user"], safe="")
            database = quote(name, safe="")
            host = config["host"]
            if host.startswith("/"):
                dsn = f"postgresql://{user}@/{database}?{urlencode({'host': host})}"
            else:
                authority = f"[{host}]" if host == "::1" else host
                dsn = f"postgresql://{user}@{authority}/{database}"
            # Both transports inherit PGPORT from the same environment as the
            # owner connection; socket DSNs contain only their host parameter.
            report = root / f"v{version}-results.xml"
            env = {
                **os.environ,
                "SALES_TEST_DATABASE_URL": dsn,
                "SALES_TEST_ROLE": role,
                "SALES_TEST_WORKSPACE": "demo-sales-workspace",
                "PYTHONDONTWRITEBYTECODE": "1",
            }
            print(f"Historical V{version} only; owner seeds followed by restricted archive calls", flush=True)
            tests = (["tests/integration/test_feishu_test_archive.py", str(source / "tests/test_feishu_test_archive_contract.py")]
                     if version == 108 else ["tests/integration/test_feishu_notification_archive_retention.py",
                                             "-k", "not current_schema_blocks_v117_archive_entry_point"])
            process = await asyncio.create_subprocess_exec(
                sys.executable, "-m", "pytest", *tests,
                "-q", "-p", "no:cacheprovider", f"--junitxml={report}", env=env, cwd=str(BACKEND),
            )
            if await process.wait():
                raise RuntimeError(f"Historical V{version} archive verification failed")
            try:
                results = ElementTree.parse(report).getroot()  # noqa: S314 - generated by the local pytest subprocess
            except (OSError, ElementTree.ParseError) as exc:
                raise RuntimeError(f"Historical V{version} archive verification produced no valid JUnit report") from exc
            cases = results.findall(".//testcase")
            skipped = len(results.findall(".//skipped"))
            failures = len(results.findall(".//failure"))
            errors = len(results.findall(".//error"))
            print(
                f"Historical V{version} coverage: {len(cases)} tests, {skipped} skipped, "
                f"{failures} failures, {errors} errors",
                flush=True,
            )
            if not cases or skipped or failures or errors:
                raise RuntimeError(
                    f"Historical V{version} archive verification requires nonempty coverage with no skips or failures"
                )

        runner.migrate = migrate_v108
        try:
            await runner.main(serve=verify)
        finally:
            runner.migrate = original_migrate


if __name__ == "__main__":
    asyncio.run(main())
